return {
  all = require 'reiterate.all',
  any = require 'reiterate.any',
  chain = require 'reiterate.chain',
  chiterator = require 'reiterate.chiterator',
  collect = require 'reiterate.collect',
  coro = require 'reiterate.coro',
  count = require 'reiterate.count',
  counter = require 'reiterate.counter',
  enumerate = require 'reiterate.enumerate',
  filter = require 'reiterate.filter',
  fold = require 'reiterate.fold',
  map = require 'reiterate.map',
  once = require 'reiterate.once',
  reduce = require 'reiterate.reduce',
  skip = require 'reiterate.skip',
  skip_while = require 'reiterate.skip_while',
  take = require 'reiterate.take',
  take_while = require 'reiterate.take_while',
  zip = require 'reiterate.zip',
}
